reflex:
  ros__parameters:
    service_names: 
      - '/record'
      - '/fatique'

memory: 
  ros__parameters: 
    topics:
      - '/button_state:std_msgs/msg/Bool'
        
    parent_folder: 'bags/'

fatique:
  ros__parameters:
    time_out: 10.0