path/circle_yaw:
  ros__parameters:
    freq: 30
    wz: 1.0
    

eyes:
  ros__parameters:
    capture_frequency: 10.0

reflex:
  ros__parameters:
    service_names: 
      # - '/record'
      - '/attitude/reset_ctrl'
      - '/depth/reset_ctrl'
      - '/input/start_and_stop'
      - '/fatique'
      #- '/path/circle_reset'

memory:
  ros__parameters:
    topics:
      - '/button_state:std_msgs/msg/Bool'
      - '/command:std_msgs/msg/Int32MultiArray'
      - '/input/omega_m:std_msgs/msg/Float32'
      - '/input/A_m:std_msgs/msg/Float32'
      - '/input/A_d:std_msgs/msg/Float32'
      - '/input/alpha_d:std_msgs/msg/Float32'
      - '/input/alpha_m:std_msgs/msg/Float32'
      - '/input/theta_m:std_msgs/msg/Float32'
      - '/input/theta_d:std_msgs/msg/Float32'
      - '/imu/data:sensor_msgs/msg/Imu'
      - '/gps_data:sensor_msgs/msg/NavSatFix'
      - '/ms5837/pose:geometry_msgs/msg/PoseWithCovarianceStamped'
      - '/est/odom:nav_msgs/msg/Odometry'
      - '/camera_1:sensor_msgs/msg/Image'
      - '/camera_2:sensor_msgs/msg/Image'
      - '/attitude/q_ref:geometry_msgs/msg/Quaternion'
      - '/attitude/roll_set:std_msgs/msg/Float32'
      - '/attitude/pitch_set:std_msgs/msg/Float32'
      - '/attitude/yaw_set:std_msgs/msg/Float32'
      - '/depth/z_set:std_msgs/msg/Float32'
    parent_folder: 'bags/circle_path'

fatique:
  ros__parameters:
    time_out: 30.0
