attitude/w_ctrl:
  ros__parameters:
    freq: 30
     # PID settings: | kp | ki | kd | min | max | filter (0 = full filtering, 1 = no filtering) |
    wx_pid_settings: [30.0, 0.0, 0.0, -30.0, 30.0, 0.5]  # alpha_d
    wy_pid_settings: [10.0, 5.0, 1.0, -45.0, 45.0, 0.5]  # theta_m
    wz_pid_settings: [-60.0, 1.0, 0.0, -60.0, 60.0, 0.5]  # A_d

attitude/q_ctrl: 
  ros__parameters:
    freq: 30
    attitude_gains: [0.3, 0.3, 0.3]  # Kp for attitude control in roll, pitch, yaw