input/ctrl:
  ros__parameters:
    freq: 30
    angle_range: [-60, 60]
    pwm_range: [19500, 43500]
    
    start_wing: [0.8, 60.0, 0.0, 0.0, 0.0 ] # | omega_m | A_m | A_d | alpha_m | alpha_d |
    start_flap: [0.0, -8.0]           # | theta_m | theta_d |

    clamp_flap: [-40, 40]
