depth/ctrl:
  ros__parameters:
    freq: 30
    # PID settings: | kp | ki | kd | min | max | filter (0 = full filtering, 1 = no filtering) |
    pid_settings: [1.0, 0.0, 0.1, -2.0, 2.0, 0.9]  # PID settings for z
    feedback_field: 'z'  # Field in the odom message to use for depth control